# Generated by Django 4.2 on 2024-07-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('L', 'Lagartija'), ('A', 'Agua'), ('P', 'Planta'), ('E', 'Electrico'), ('T', 'Tierra')], max_length=30),
        ),
    ]
